config/routes.rb
Rails.application.routes.draw do

  root to: "jobs#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


resources :users do
  resources :ships
end

resources :users do
  resources :jobs
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  has_and_belongs_to_many :ships
  belongs_to :user
end

app/models/ship.rb
class Ship < ApplicationRecord
  has_and_belongs_to_many :jobs
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 has_many :jobs
 has_many :ships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find_by_id(params[:id])
  end

  def create
    @user = current_user
    @job = Job.new(job_params)
    @job.user_id = @user.id

    @ships = Ship.where(:id => params[:select_ships])
    @job.ships << @ships

      if @job.save!
      end
    redirect_to "/"
  end

  def new
    @job = Job.new
  end

  def update
      @job = Job.find(params[:id])
      @job.update_attributes(job_params)
      # @job.ships << ship.id
      @ships = Ship.all

      # redirect_to infos_path
      redirect_to "/"
  end

  private

    def job_params
      params.require(:job).permit(:description, :origin, :destination, :cost, :containers, :ship_id)
    end


end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  def index
    @ships = Ship.all
  end

  def show
    @ship = Ship.find_by_id(params[:id])
  end

  def create
    @user = current_user
    @ship = Ship.new(ship_params)
    @ship.user_id = @user.id
    if @ship.save!
    end
    redirect_to user_ships_path
  end

  def new
    @ship = Ship.new
  end


  private

    def ship_params
      params.require(:ship).permit(:name, :location, :capacity)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/open_jobs_helper.rb
module OpenJobsHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/edit.html.erb
<h1>Jobs#edit</h1>
<p>Find me in app/views/jobs/edit.html.erb</p>

app/views/jobs/index.html.erb
<h1>Jobs#index</h1>
<p>Find me in app/views/jobs/index.html.erb</p>

<table>
    <thead>
        <th>Description</th>
        <th>Origin</th>
        <th>Destination</th>
        <th>Cost</th>
        <th>Containers</th>
        <th>Ships</th>
    </thead>
    <tbody>
<% @jobs.each do |j| %>
    <tr>
        <td><%= j.description %></td>
        <td><%= j.origin %></td>
        <td><%= j.destination %></td>
        <td><%= j.cost %></td>
        <td><%= j.containers %></td>
        <td><%= j.ship_ids %></td>
    </tr>
<% end %>
    </tbody>
</table>

app/views/jobs/new.html.erb
<h1>Jobs#new</h1>
<p>Find me in app/views/jobs/new.html.erb</p>


<%= form_for :job, url: user_jobs_path do |f| %>
    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :origin %>
    <%= f.text_field :origin %>

    <%= f.label :destination %>
    <%= f.text_field :destination %>

    <%= f.label :cost %>
    <%= f.number_field :cost, class: :text_field, step: :any %>

    <%= f.label :containers %>
    <%= f.number_field :containers, class: :text_field, step: :any %>

    <%= f.label :ships %>
    <%= select_tag "select_ships", options_from_collection_for_select(Ship.all, 'id', 'name',@job.ships.map{ |j| j.id }), :multiple => true %>


<%= f.submit %>
  <% end %>

app/views/jobs/show.html.erb
<h1>Jobs#show</h1>
<p>Find me in app/views/jobs/show.html.erb</p>


<%= check_box_tag(:pet_dog) %>
<%= label_tag(:pet_dog, "I own a dog") %>
<%= check_box_tag(:pet_cat) %>
<%= label_tag(:pet_cat, "I own a cat") %>

<%= text_field(:person, :name) %>


<select name="city_id" id="city_id">
  <option value="1">Lisbon</option>
  <option value="2">Madrid</option>
  ...
  <option value="12">Berlin</option>
</select>

<p><%= @job.description %></p>
<p><%= @job.origin %></p>
<p><%= @job.destination %></p>
<p><%= @job.cost %></p>
<p><%= @job.containers %></p>
<p><%= @job.ships.last.name%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shipping</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
      <nav>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", user_jobs_path(current_user.id) %></li>
          <li><%= link_to "Build Ship", new_user_ship_path(current_user.id) %></li>
          <li><%= link_to "New Job", new_user_job_path(current_user.id) %></li>
        </ul>
      <% end %>
    </nav>


  <body>
    <img src="/assets/boat.png"/>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

    <%= yield %>
  </body>
</html>

app/views/ships/edit.html.erb
<h1>Ships#edit</h1>
<p>Find me in app/views/ships/edit.html.erb</p>

app/views/ships/index.html.erb
<h1>Ships#index</h1>
<p>Find me in app/views/ships/index.html.erb</p>

<% @ships.each do |f| %>
      <p><%= f.name %></p>
      <p><%= f.capacity %></p>
      <p><%= f.location %></p>
<% end %>

app/views/ships/new.html.erb
<h1>Ships#new</h1>
<p>Find me in app/views/ships/new.html.erb</p>

<%= form_for :ship, url: user_ships_path do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :capacity %>
    <%= f.text_field :capacity %>

    <%= f.label :location %>
    <%= f.text_field :location %>
<%= f.submit %>
  <% end %>

app/views/ships/show.html.erb
<h1>Ships#show</h1>
<p>Find me in app/views/ships/show.html.erb</p>

<p><%= @ship.name %></p>
<p><%= @ship.capacity %></p>
<p><%= @ship.location %></p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>


<% @users.each do |u| %>
      <p><%= u.email %></p>
      
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<p><%= @user.email %></p>
<p><%= @user.encrypted_password %></p>